// CONTACTS ACTION
export const GET_CONTACTS = "GET_CONTACTS"
export const GET_BLOCKED_CONTACTS = "GET_BLOCKED_CONTACTS"
export const DELETE_CONTACT = "DELETE_CONTACT"
export const BLOCK_CONTACT = "BLOCK_CONTACT"
export const CONTACT_ERROR = "CONTACT_ERROR"
export const CONTACT_SUCCESS = "CONTACT_SUCCESS"
export const CONTACT_LOADING = "CONTACT_LOADING"

// MESSAGES ACTION
export const GET_MESSAGES = "GET_MESSAGES"
export const GET_ALL_MESSAGES = "GET_ALL_MESSAGES"
export const GET_SENT_MESSAGES = "GET_SENT_MESSAGES"
export const GET_STARRED_MESSAGES = "GET_STARRED_MESSAGES"
export const GET_ARCHIVED_MESSAGES = "GET_ARCHIVED_MESSAGES"
export const MESSAGE_LOADING = "MESSAGE_LOADING"
export const DELETE_MESSAGE = "DELETE_MESSAGE"
export const UPDATE_ARCHIVE_MESSAGE = "UPDATE_ARCHIVE_MESSAGE"
export const UPDATE_STARRED_MESSAGE = "UPDATE_STARRED_MESSAGE"


// CONTACT REQUEST ACTION
export const GET_CONTACT_REQUEST = "GET_CONTACT_REQUEST"
export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST"
export const BLOCK_CONTACT_REQUEST = "BLOCK_CONTACT_REQUEST"
export const CONTACT_REQUEST_ERROR = "CONTACT_REQUEST_ERROR"
export const ACCEPT_CONTACT_REQUEST = "ACCEPT_CONTACT_REQUEST"
export const CONTACT_REQUEST_LOADING = "CONTACT_REQUEST_LOADING"

// TRANSACTIONS ACTION
export const GET_TRANSACTIONS = "TRANSACTIONS"
export const TRANSACTION_LOADING = "TRANSACTION_LOADING"


// PAYMENT REQUEST ACTION
export const GET_PAYMENT_REQUEST = "GET_PAYMENT_REQUEST"
export const REJECT_PAYMENT_REQUEST = "REJECT_PAYMENT_REQUEST"
export const PAYMENT_REQUEST_LOADING = "PAYMENT_REQUEST_LOADING"

// PAYOUTS ACTION
export const GET_PAYOUTS = "GET_PAYOUTS"
export const PAYOUTS_LOADING = "PAYOUTS_LOADING"

export const GET_INVOICE = "GET_INVOICE"
export const GET_PAYMENT_CONTRACT = "GET_PAYMENT_CONTRACT"

// BANK ACCOUNTS ACTION
export const GET_BANK_ACCOUNTS = "GET_BANK_ACCOUNTS"
export const GET_BANK_ACCOUNTS_LOADING = "GET_BANK_ACCOUNTS_LOADING"

// SETTINGS ACTION
export const GET_SETTINGS = "GET_SETTINGS"
export const GET_TEAM_MEMBERS = "GET_TEAM_MEMBERS"
export const GET_SHIPPING_OPTIONS = "GET_SHIPPING_OPTIONS"
export const CREATE_TERMS_AND_CONDITIONS = "CREATE_TERMS_AND_CONDITIONS"
export const GET_TERMS_AND_CONDITIONS = "GET_TERMS_AND_CONDITIONS"
export const SETTINGS_LOADING = "SETTINGS_LOADING"
export const TEAM_MEMBERS_LOADING = "TEAM_MEMBERS_LOADING"
export const CREATE_SHIPPING_OPTION = "CREATE_SHIPPING_OPTION"
export const CREATE_TEAM_MEMBER = "CREATE_TEAM_MEMBER"
export const EDIT_TEAM_MEMBER = "EDIT_TEAM_MEMBER"
export const DELETE_TEAM_MEMBER = "DELETE_TEAM_MEMBER"
export const EDIT_SHIPPING_OPTION = "EDIT_SHIPPING_OPTION"
export const DELETE_SHIPPING_OPTION = "DELETE_SHIPPING_OPTION"

// SLYDOCOMMERCE ACTION
export const GET_ORDERS = "GET_ORDERS"
export const ORDER_MESSAGE = "ORDER_MESSAGE"
export const GET_PRODUCTS = "GET_PRODUCTS"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const GET_SERVICES = "GET_SERVICES"
export const GET_SLYDO_COMMERCE_LOADING = "GET_SLYDO_COMMERCE_LOADING"
export const GET_CATEGORIES = "GET_CATEGORIES"
export const GET_CONDITION = "GET_CONDITION"
export const VIEW_ORDERS = "VIEW_ORDERS"
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS"
export const UPDATE_ORDER_NOTES = "UPDATE_ORDER_NOTES"
export const GET_SERVICE_CATEGORIES = "GET_SERVICE_CATEGORIES"
export const CREATE_SERVICES = "CREATE_SERVICES"
export const UPDATE_SERVICE = "UPDATE_SERVICE"
export const DELETE_SERVICE = "DELETE_SERVICE"

// BLOG ACTION
export const GET_BLOG = "GET_BLOG"
export const GET_BLOG_POSTS = "GET_BLOG_POSTS"
export const GET_BLOG_POSTS_LOADING = "GET_BLOG_POSTS_LOADING"
export const CREATE_BLOG_POST = "CREATE_BLOG_POST"
export const DELETE_BLOG_POST = "DELETE_BLOG_POST"
export const UPDATE_BLOG_POST = "UPDATE_BLOG_POST"
// INTEGRATIONS ACTION
export const GET_INTEGRATIONS = "GET_INTEGRATIONS"
export const GET_INTEGRATIONS_LOADING = "GET_INTEGRATIONS_LOADING"
export const GET_API_KEYS_INTEGRATIONS = "GET_API_KEYS_INTEGRATIONS"
export const CREATE_API_KEY_INTEGRATIONS = "CREATE_API_KEY_INTEGRATIONS"
export const EDIT_WEBHOOK = "EDIT_WEBHOOK"
export const DELETE_API_KEY_INTEGRATIONS = "DELETE_API_KEY_INTEGRATIONS"
export const CREATE_INTEGRATION = "CREATE_INTEGRATION"
export const DELETE_INTEGRATION = "DELETE_INTEGRATION"

// AUTH ACTION
export const LOGIN = "LOGIN"
export const USER_LOADING = "USER_LOADING"
export const USER_ERROR = "USER_ERROR"

//PROFILE ACTION
export const GET_PROFILE = "GET_PROFILE"
export const GET_OPENING_HOURS = "GET_OPENING_HOURS"
export const PROFILE_LOADING = "PROFILE_LOADING"
export const UPDATE_PROFILE = "UPDATE_PROFILE"
export const UPDATE_ADRESS = "UPDATE_ADRESS"
export const UPDATE_BIO = "UPDATE_BIO"
export const UPDATE_OPENING_HOURS = "UPDATE_OPENING_HOURS"
export const UPDATE_WALLPAPER = "UPDATE_WALLPAPER"
export const UPDATE_PROFILE_IMAGE = "UPDATE_PROFILE_IMAGE"
